name: sqlparse

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    name: Build+test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # test a bunch of toolchains on ubuntu
        rust:
          - stable
        os: [ubuntu-latest]
        # but only stable on macos/windows (slower platforms)
        include:
          - os: macos-latest
            rust: stable
          - os: windows-latest
            rust: stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: cargo build (debug; default features)
        run: cargo build

      - name: cargo build (debug; default features)
        run: cargo bench

      - name: cargo test (debug; all features)
        run: cargo test
        env:
          RUST_BACKTRACE: 1
